variables:
  REGION: asia-southeast1
  IMAGE_NAME: tc-tools
  APP_NAME_API: tc-tools
  APP_NAME_API_WORKER: dwf-twitter-queue
  APP_NAME_API_SCHDULE: dwf-twitter-schedule
  APP_NAME_API_TC_WORKER: dwf-twitter-tc-queue
  APP_NAME_API_RESULTS_WORKER: dwf-twitter-results-queue
  CONTAINER_REPO_ASIA_STAG: 968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/stag/tc-tools

  NAMESPACE_STAG: tc-stag
  NAMESPACE_PROD: tc-prod

  HELM_VALUE_FOLDER: dwf
  FULLREPO_ASIA_STAG: $CONTAINER_REPO_ASIA_STAG:$CI_COMMIT_SHA
  FULLREPO_ASIA_PROD: $CONTAINER_REPO_ASIA_PROD:$CI_COMMIT_SHA

  HELM_VALUE: ${CI_COMMIT_REF_NAME}
  HELM_VERSION: 3.0.1
  HELM_CRONJOB_VERSION: 0.1.9
  AWS_REGION: ap-southeast-1
  GITLAB_TOKEN: $GITLAB_RUNNER_TOKEN


  SUBMODULE_REPO: https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/twitter-crawler/tc-lib.git
  SUBMODULE_BRANCH: stag

  DOCKER_DRIVER: overlay
 # DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

.kubectl_config: &kubectl_config
  - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        aws eks --region $AWS_REGION update-kubeconfig --name esol-staging-cluster
      fi

.predeploy: |
  apk add --no-cache  bash git  python3 py3-pip curl
  pip3 install --upgrade pip 
  pip3 install --no-cache-dir awscli==1.25.78
  helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.12.0
  helm repo add helm-template s3://esol-helm-template
  helm repo add helm-template-cronjob s3://esol-helm-template/cronjob
  helm pull s3://esol-helm-template/helm-template-$HELM_VERSION.tgz --untar=true
  helm pull s3://esol-helm-template/cronjob/helm-template-cronjob-$HELM_CRONJOB_VERSION.tgz --untar=true

build_stag:
  image: docker:19.03.1
  tags:
  - esol-stag-test
  stage: build
  services:
  - docker:19.03.1-dind
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
    - ./node_modules/
  before_script:
    - apk add --no-cache curl jq python3 py3-pip wget git bash
    - pip3 install awscli
    - git submodule add -f --branch stag https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/twitter-crawler/tc-lib.git lib
    - git submodule sync --recursive
    - git submodule update --init --remote --recursive

    - export VERIFY_CHECKSUM=false && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod +x ./get_helm.sh && ./get_helm.sh
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.38.0/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
    - git submodule sync --recursive
    - git submodule update --init --remote --recursive
  script:
    - docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $CONTAINER_REPO_ASIA_STAG
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$IMAGE_NAME#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
        cat skaffold.yaml
      fi
    - /usr/local/bin/skaffold build -p profile-stag --file-output=build_sync.json
  only:
    refs:
      - stag
  artifacts:
    paths:
    - build_sync.json

deploy_APP_NAME_API_stag:
  stage: deploy
  image:  968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/base-cicd:alpine-helm-3.0.1
  tags:
  - esol-stag
  script:
    - *kubectl_config
    - mv /apps/helm-template .
    - mv /apps/helm-template-cronjob .
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_API#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
      # https://gitlab.rinznetwork.com/twitter-crawler/cicd/tools.git
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/twitter-crawler/cicd/tools.git
    - mv tools/${APP_NAME_API}-stag.yaml .
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_API}-stag   -a build_sync.json
  retry: 2
  only:
    refs:
      - stag

deploy_APP_NAME_API_WORKER_stag:
  stage: deploy
  image:  968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/base-cicd:alpine-helm-3.0.1
  tags:
  - esol-stag
  script:
    - *kubectl_config
    - mv /apps/helm-template .
    - mv /apps/helm-template-cronjob .
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_API_WORKER#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/twitter-crawler/cicd/tools.git
    - mv tools/${APP_NAME_API_WORKER}-stag.yaml .
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_API_WORKER}-stag   -a build_sync.json

  only:
    refs:
      - stag


deploy_APP_NAME_API_SCHDULE_stag:
  stage: deploy
  image:  968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/base-cicd:alpine-helm-3.0.1
  tags:
  - esol-stag
  script:
    - *kubectl_config
    - mv /apps/helm-template .
    - mv /apps/helm-template-cronjob .
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_API_SCHDULE#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/twitter-crawler/cicd/tools.git
    - mv tools/${APP_NAME_API_SCHDULE}-stag.yaml .
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_API_SCHDULE}-stag   -a build_sync.json

  only:
    refs:
      - stag

deploy_APP_NAME_API_TC_WORKER_stag:
  stage: deploy
  image:  968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/base-cicd:alpine-helm-3.0.1
  tags:
  - esol-stag
  script:
    - *kubectl_config
    - mv /apps/helm-template .
    - mv /apps/helm-template-cronjob .
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_API_TC_WORKER#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/twitter-crawler/cicd/tools.git
    - mv tools/${APP_NAME_API_TC_WORKER}-stag.yaml .
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_API_TC_WORKER}-stag   -a build_sync.json

  only:
    refs:
      - stag

deploy_APP_NAME_API_RESULTS_WORKER_stag:
  stage: deploy
  image:  968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/base-cicd:alpine-helm-3.0.1
  tags:
  - esol-stag
  script:
    - *kubectl_config
    - mv /apps/helm-template .
    - mv /apps/helm-template-cronjob .
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_API_RESULTS_WORKER#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/twitter-crawler/cicd/tools.git
    - mv tools/${APP_NAME_API_RESULTS_WORKER}-stag.yaml .
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_API_RESULTS_WORKER}-stag   -a build_sync.json

  only:
    refs:
      - stag
